"""Adicionado campo UPDATED_AT

Revision ID: 0a86cd531014
Revises: 8b870c738cde
Create Date: 2024-07-17 21:00:14.194266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a86cd531014'
down_revision: Union[str, None] = '8b870c738cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('users', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_at', sa.DATETIME(), nullable=False))
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
